site_name: Numerical Analysis ATM

site_description: The Numerical Analysis Method I have learned in "Numerical Analysis" 2022 Fall | Prof. Shu-chih Yang (楊 舒芝)

site_author: 1chooo(Hugo ChunHo Lin)

site_url: https://1chooo.github.io/ATM-Numerical-Analysis/

repo_url: https://github.com/1chooo/ATM-Numerical-Analysis

copyright: Copyright &copy; 2023 1chooo (Hugo ChunHo Lin)

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.top
        - navigation.tabs
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    # favicon: assets/favicon.ico
    icon:
        logo: logo

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: True
        # validate_nb: True
        #   ignore_h1_titles: True
        #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - toc:
        permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1chooo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/1chooo___



nav:
    - Home: index.md
    # - Installation: installation.md
    # - Usage: usage.md
    - Course Note:
      - course_note/Week01.md
      - course_note/Week02.md
      - course_note/Week03.md
      - course_note/Week04.md
      - course_note/Week05.md
      - course_note/Week06.md
      - course_note/Week07.md
      - course_note/Week08.md
      - course_note/Week09.md
      - course_note/Week10.md
      - course_note/Week11.md
      - course_note/Week12.md
    - Assignment:
      - assignment/a1.py
    - Past Exam:
      - 2022 Fall:
        - past_exam/2022_fall/read_file.ipynb
        - past_exam/2022_fall/22_fall_q1.ipynb
        - past_exam/2022_fall/22_fall_q2.ipynb
        - past_exam/2022_fall/22_fall_q3.ipynb
        - past_exam/2022_fall/22_fall_q4.ipynb


    - Contributing: contributing.md

    - Reference: reference.md
    - Report Issues: https://github.com/1chooo/ATM-Numerical-Analysis/issues
